apiVersion: v1
kind: Service
metadata:
  name: social-media-service
  namespace: social-media
  labels:
    app: social-media-app
spec:
  type: NodePort
  selector:
    app: social-media-app
  ports:
  - name: http
    port: 80
    targetPort: 3000
    nodePort: 30080
