pipeline {
    agent any

    environment {
        IMAGE_NAME = "react-docker-app"
        CONTAINER_NAME = "react-app"
    }

    stages {

        stage('Clone Repository') {
            steps {
                echo "Repository already checked out by Jenkins"
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Remove Old Container') {
            steps {
                sh 'docker rm -f $CONTAINER_NAME || true'
            }
        }

        stage('Run Docker Container') {
            steps {
                sh 'docker run -d --name $CONTAINER_NAME -p 8080:80 $IMAGE_NAME'
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }

        failure {
            echo 'Pipeline failed!'
        }
    }
}