pipeline {
    agent any

    stages {

        stage('Clone Repository') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t dockerizedjenkinsdemo .'
            }
        }

        stage('Stop Old Container') {
            steps {
                bat 'docker stop flask-container || exit /B 0'
                bat 'docker rm flask-container || exit /B 0'
            }
        }

        stage('Run New Container') {
            steps {
                bat 'docker run -d --name flask-container -p 5000:5000 dockerizedjenkinsdemo'
            }
        }

    }
}