pipeline {
    agent any

    stages {

        stage('Checkout Source Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/pratiklakra38/devops-lab.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t hello-flask:latest .'
            }
        }

        stage('List Docker Images') {
            steps {
                sh 'docker images'
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker tag hello-flask:latest YOUR_DOCKERHUB_USERNAME/hello-flask:latest'
                sh 'docker push YOUR_DOCKERHUB_USERNAME/hello-flask:latest'
            }
        }
    }

    post {
        success {
            echo 'Pipeline executed successfully!'
        }
    }
}