
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: social-app
  template:
    metadata:
      labels:
        app: social-app
    spec:
      containers:
      - name: social-app
        image: social-app:v1
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "250m"
