pipeline {
    agent none

    stages {

        stage('Compile') {
            agent { label 'compile' }

            steps {
                sh 'mvn clean compile'
            }
        }

        stage('Test') {
            agent { label 'test' }

            steps {
                sh 'mvn test'
            }
        }

        stage('Package') {
            agent { label 'compile' }

            steps {
                sh 'mvn package -DskipTests'
            }
        }
    }

    post {
        success {
            echo 'Portfolio pipeline completed successfully!'
        }

        failure {
            echo 'Portfolio pipeline failed.'
        }
    }
}