apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: project8-auth:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
          env:
            - name: AUTH_PORT
              valueFrom:
                configMapKeyRef:
                  name: project8-config
                  key: AUTH_PORT