pipeline {
    agent none

    stages {

        stage('Build') {
            agent { label 'agent-1' }

            steps {
                git branch: 'main',
                    url: 'https://github.com/parth2965/Project_4.git'

                dir('portfolio-app') {
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            agent { label 'agent-2' }

            steps {
                git branch: 'main',
                    url: 'https://github.com/parth2965/Project_4.git'

                dir('portfolio-app') {
                    bat 'mvn test'
                }
            }
        }

        stage('Package') {
            agent { label 'agent-1' }

            steps {
                git branch: 'main',
                    url: 'https://github.com/parth2965/Project_4.git'

                dir('portfolio-app') {
                    bat 'mvn package'
                }
            }
        }
    }
}