version: '3'
services:
  jenkins-master:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
  jenkins-agent-1:
    image: jenkins/inbound-agent
    environment:
      - JENKINS_URL=http://jenkins-master:8080
  jenkins-agent-2:
    image: jenkins/inbound-agent
    environment:
      - JENKINS_URL=http://jenkins-master:8080