apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: frontend-service:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: USER_SERVICE_URL
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: PRODUCT_SERVICE_URL
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: ORDER_SERVICE_URL
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: microservices-secret
                  key: API_KEY