# mongo-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ29hZG1pbg==      # base64 of "mongoadmin"
  mongo-password: c2VjcmV0MTIz      # base64 of "secret123"
  