apiVersion: v1
kind: Service
metadata:
  name: social-media-service
  namespace: social-media
spec:
  selector:
    app: social-media
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
