apiVersion: apps/v1
kind: Deployment
metadata:
  name: socialconnect
  labels:
    app: socialconnect
spec:
  replicas: 2
  selector:
    matchLabels:
      app: socialconnect
  template:
    metadata:
      labels:
        app: socialconnect
    spec:
      containers:
      - name: socialconnect
        image: socialconnect:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "100m"

