FROM node:20-alpine
ARG SERVICE
WORKDIR /app
COPY services/${SERVICE}/package.json ./package.json
RUN npm install --omit=dev
COPY shared ./shared
COPY services/${SERVICE}/server.js ./server.js
CMD ["node","server.js"]
