pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Checking out source code...'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t flask-app .'
            }
        }

        stage('Run Docker Container') {
            steps {
                bat 'docker rm -f flask-container || exit 0'
                bat 'docker run -d -p 5001:5000 --name flask-container flask-app'
            }
        }
    }
}