apiVersion: v1
kind: Pod
metadata:
  name: load-generator
spec:
  containers:
    - name: load-generator
      image: busybox:latest
      command:
        - /bin/sh
        - -c
        - |
          while true; do
            wget -q -O- http://social-media-service;
          done
  restartPolicy: Always
