pipeline {
    agent none

    stages {

        stage('Build') {
            agent { label 'agent1' }
            steps {
                echo 'Building on agent1...'
                bat 'mvn clean compile'
            }
        }

        stage('Test') {
            agent { label 'agent2' }
            steps {
                echo 'Testing on agent2...'
                bat 'mvn test'
            }
        }

        stage('Package') {
            agent { label 'agent1' }
            steps {
                echo 'Packaging application...'
                bat 'mvn package'
            }
        }
    }
}