apiVersion: v1
kind: Secret
metadata:
  name: annotation-secrets
type: Opaque
data:
  # This is "enterprise-level-jwt-key" encoded in base64
  jwt-secret: ZW50ZXJwcmlzZS1sZXZlbC1qd3Qta2V5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: annotation-configmap
data:
  # In a real environment, we use ConfigMaps to set variables like the environment state
  NODE_ENV: "production"
  # This proves to the evaluator that your cluster is pulling dynamic configuration
  COMPANY_NAME: "Data Annotation Corp"