pipeline {
    agent none

    stages {
        stage('Compile') {
            agent { label 'agent1' }

            steps {
                echo 'Compiling on Agent 1'

                dir('23070122040_AparnaNair/Project_4/maven-demo') {
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            agent { label 'agent2' }

            steps {
                echo 'Testing on Agent 2'

                dir('23070122040_AparnaNair/Project_4/maven-demo') {
                    bat 'mvn test'
                }
            }
        }
    }

    post {
        success {
            echo 'Project 4 completed successfully!'
        }
    }
}