apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  labels:
    app: ecommerce-app
    tier: auth-service
type: Opaque
stringData:
  jwt-secret: "ecommerce-jwt-super-secret-key-2026"
  admin-password: "admin123"
  db-password: "secretpassword"
