apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: ecommerce-app
    tier: database
type: Opaque
stringData:
  mongo-root-username: admin
  mongo-root-password: secretpassword
