apiVersion: v1
kind: Secret
metadata:
  name: order-secret
  labels:
    app: ecommerce-app
    tier: order-service
type: Opaque
stringData:
  api-secret-key: "ord-sec-key-live-998811"
  db-password: "secretpassword"
