apiVersion: apps/v1
kind: Deployment
metadata:
  name: retailapp-deployment
  labels:
    app: retailapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: retailapp
  template:
    metadata:
      labels:
        app: retailapp
    spec:
      containers:
        - name: retailapp
          image: retailapp:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
