apiVersion: v1
kind: Service
metadata:
  name: retailapp-service
spec:
  type: NodePort
  selector:
    app: retailapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081
      nodePort: 30081
